# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u4ee3\u7406\u5546\u540d\u79f0')),
                ('contacts', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('memo', models.CharField(blank=True, max_length=128, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u4ee3\u7406\u5546',
                'verbose_name_plural': '\u4ee3\u7406\u5546',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(verbose_name='\u7269\u7406cpu\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(verbose_name='cpu\u6838\u6570')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CPU\u90e8\u4ef6',
                'verbose_name_plural': 'CPU\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=32, verbose_name='\u90e8\u95e8\u7f16\u53f7')),
                ('name', models.CharField(max_length=32, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('leader', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u90e8\u95e8\u9886\u5bfc')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Department', verbose_name='\u4e0a\u7ea7\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u90e8\u95e8\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('iface_type', models.CharField(choices=[(b'SATA', b'SATA'), (b'SAS', b'SAS'), (b'SCSI', b'SCSI'), (b'SSD', b'SSD')], default=b'SAS', max_length=64, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u5458\u5de5\u59d3\u540d')),
                ('position', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u804c\u4f4d')),
                ('emp_sn', models.IntegerField(unique=True, verbose_name='\u5458\u5de5\u7f16\u53f7')),
                ('sex', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='\u5458\u5de5\u51fa\u751f\u65e5\u671f')),
                ('hometown', models.TextField(blank=True, null=True, verbose_name='\u7956\u7c4d')),
                ('address', models.TextField(blank=True, null=True, verbose_name='\u73b0\u4f4f\u5730\u5740')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('contacts', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7d27\u6025\u8054\u7cfb\u4eba')),
                ('con_phone', models.BigIntegerField(blank=True, null=True, verbose_name='\u8054\u7cfb\u4eba\u53f7\u7801')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='\u5165\u804c\u65f6\u95f4')),
                ('status', models.CharField(choices=[(b'on', '\u5728\u804c'), (b'dimission', '\u79bb\u804c'), (b'vacation', '\u4f11\u5047')], max_length=64, verbose_name='\u5728\u804c\u72b6\u6001')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='ManuFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='\u5236\u9020\u5546\u540d\u79f0')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('memo', models.CharField(blank=True, max_length=128, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5382\u5546',
                'verbose_name_plural': '\u5382\u5546',
            },
        ),
        migrations.CreateModel(
            name='OfficeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(choices=[(b'pc', '\u53f0\u5f0f\u7535\u8111'), (b'note_pc', '\u7b14\u8bb0\u672c\u7535\u8111'), (b'printer', '\u6253\u5370\u673a'), (b'other', '\u5176\u4ed6')], max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('asset_stauts', models.IntegerField(choices=[(0, '\u4f7f\u7528\u4e2d'), (1, '\u672a\u4f7f\u7528'), (2, '\u6545\u969c\u4e2d'), (3, '\u62a5\u4fee\u4e2d'), (4, '\u62a5\u5e9f'), (5, '\u672a\u77e5')], default=0, verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('agents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Agents', verbose_name='\u4ee3\u7406\u5546')),
                ('asset_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Department', verbose_name='\u8d44\u4ea7\u6240\u5c5e\u90e8\u95e8')),
                ('manufactory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ManuFactory', verbose_name='\u5236\u9020\u5546')),
            ],
            options={
                'verbose_name': '\u529e\u516c\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u529e\u516c\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(max_length=128, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(verbose_name='\u5185\u5b58\u5927\u5c0f(MB)')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
                'verbose_name_plural': '\u5185\u5b58',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset', verbose_name='\u8d44\u4ea7'),
        ),
        migrations.AddField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Department', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='disk',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset'),
        ),
    ]
