# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset', verbose_name='\u8d44\u4ea7'),
        ),
    ]
