# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170505_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Employee', verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8\xe9\xa2\x86\xe5\xaf\xbc'),
        ),
    ]
