# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20170508_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u79bb\u804c\u65f6\u95f4'),
        ),
    ]
