# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20170508_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u652f\u6301\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u652f\u6301\u7535\u8bdd'),
        ),
    ]
