# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20170508_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '\u91c7\u8d2d'), (1, '\u9886\u7528'), (2, '\u9001\u4fee'), (3, '\u62a5\u5e9f'), (4, '\u6545\u969c')], verbose_name='\u8d44\u4ea7\u52a8\u6001')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.OfficeAsset', verbose_name='\u8d44\u4ea7')),
            ],
        ),
    ]
