# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_assetuseinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetuseinfo',
            options={'verbose_name': '\u8d44\u4ea7\u52a8\u6001\u8868', 'verbose_name_plural': '\u8d44\u4ea7\u52a8\u6001\u8868'},
        ),
    ]
